Resources:
  cloudfrontDist:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
         Ref: websiteHostNames 
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
              HTTPPort: 80
              HTTPSPort: 443
            DomainName:
              "Fn::Join": [ "", [ Ref: websiteBucket, .s3-website-, Ref: AWS::Region, .amazonaws.com ] ]
            Id:
              Ref: websiteBucket
        Logging:
          IncludeCookies: False
          Bucket:
            "Fn::GetAtt": [ logBucket, DomainName ]
          Prefix: "cflogs"
        CacheBehaviors:
          - ViewerProtocolPolicy: redirect-to-https
            DefaultTTL: 604800
            AllowedMethods:
              - HEAD
              - GET
            CachedMethods:
              - HEAD
              - GET
            MinTTL: 0
            Compress: True
            ForwardedValues:
              QueryString: False
              Cookies:
                Forward: none
            TargetOriginId:
              Ref: websiteBucket
            PathPattern: /css/*.css
          - ViewerProtocolPolicy: redirect-to-https
            DefaultTTL: 604800
            AllowedMethods:
              - HEAD
              - GET
            CachedMethods:
              - HEAD
              - GET
            MinTTL: 0
            Compress: True
            ForwardedValues:
              QueryString: False
              Cookies:
                Forward: none
            TargetOriginId:
              Ref: websiteBucket
            PathPattern: /js/*.js
          - ViewerProtocolPolicy: redirect-to-https
            DefaultTTL: 86400
            AllowedMethods:
              - HEAD
              - GET
            CachedMethods:
              - HEAD
              - GET
            MinTTL: 0
            Compress: True
            ForwardedValues:
              QueryString: False
              Cookies:
                Forward: none
            TargetOriginId:
              Ref: websiteBucket
            PathPattern: '*.jpg'
          - ViewerProtocolPolicy: redirect-to-https
            DefaultTTL: 86400
            AllowedMethods:
              - HEAD
              - GET
            CachedMethods:
              - HEAD
              - GET
            MinTTL: 0
            Compress: True
            ForwardedValues:
              QueryString: False
              Cookies:
                Forward: none
            TargetOriginId:
              Ref: websiteBucket
            PathPattern: '*.png'
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 1800
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          MinTTL: 0
          Compress: True
          ForwardedValues:
            QueryString: False
            Cookies:
              Forward: none
          TargetOriginId:
            Ref: websiteBucket
        ViewerCertificate:
          AcmCertificateArn:
            Ref: websiteCert
          SslSupportMethod: sni-only
        CustomErrorResponses:
          -
            ErrorCode: 403
            ErrorCachingMinTTL: 300
            ResponseCode: 403
            ResponsePagePath: "/403.html"
          -
            ErrorCode: 404
            ErrorCachingMinTTL: 300
            ResponseCode: 404
            ResponsePagePath: "/404.html"
        DefaultRootObject: "index.html"
        PriceClass: "PriceClass_100"
        Enabled: True
        

