Resources:
  websiteS3Policy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Ref: websiteBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  -
                   Ref: "websiteBucket"
                  - "/*"
            Principal: "*"
        